Update superlinter.yml

diff --git a/.github/workflows/superlinter.yml b/.github/workflows/superlinter.yml
--- a/.github/workflows/superlinter.yml
+++ b/.github/workflows/superlinter.yml
@@ -45,11 +45,15 @@ jobs:
             echo "- Python"
             echo "- JavaScript"
             echo "- JSON"
-            echo ""
-            echo "## ❌ Detected Style Errors"
           } >> "$GITHUB_STEP_SUMMARY"
 
           js_errors=$(grep -E '/.*\.js:[0-9]+:' super-linter.log || true)
+          py_errors=$(grep -E '/.*\.py:[0-9]+:' super-linter.log || true)
+          json_errors=$(grep -E '/.*\.json:[0-9]+:' super-linter.log || true)
+
+          if [[ -n "$js_errors" || -n "$py_errors" || -n "$json_errors" ]]; then
+          echo -e "\n## ❌ Detected Style Errors" >> "$GITHUB_STEP_SUMMARY"
+
           if [[ -n "$js_errors" ]]; then
             echo -e "\n### JavaScript" >> "$GITHUB_STEP_SUMMARY"
             echo '```' >> "$GITHUB_STEP_SUMMARY"
@@ -57,25 +61,24 @@ jobs:
             echo '```' >> "$GITHUB_STEP_SUMMARY"
           fi
 
-          py_errors=$(grep -E '/.*\.py:[0-9]+:' super-linter.log || true)
           if [[ -n "$py_errors" ]]; then
-            echo -e "\n### Python" >> "$GITHUB_STEP_SUMMARY"
-            echo '```' >> "$GITHUB_STEP_SUMMARY"
-            echo "$py_errors" >> "$GITHUB_STEP_SUMMARY"
-            echo '```' >> "$GITHUB_STEP_SUMMARY"
+           echo -e "\n### Python" >> "$GITHUB_STEP_SUMMARY"
+           echo '```' >> "$GITHUB_STEP_SUMMARY"
+           echo "$py_errors" >> "$GITHUB_STEP_SUMMARY"
+           echo '```' >> "$GITHUB_STEP_SUMMARY"
           fi
 
-          json_errors=$(grep -E '/.*\.json:[0-9]+:' super-linter.log || true)
           if [[ -n "$json_errors" ]]; then
-            echo -e "\n### JSON" >> "$GITHUB_STEP_SUMMARY"
-            echo '```' >> "$GITHUB_STEP_SUMMARY"
-            echo "$json_errors" >> "$GITHUB_STEP_SUMMARY"
-            echo '```' >> "$GITHUB_STEP_SUMMARY"
+           echo -e "\n### JSON" >> "$GITHUB_STEP_SUMMARY"
+           echo '```' >> "$GITHUB_STEP_SUMMARY"
+           echo "$json_errors" >> "$GITHUB_STEP_SUMMARY"
+           echo '```' >> "$GITHUB_STEP_SUMMARY"
+          fi
           fi
 
       - name: 📦 Upload Super-Linter Artifact
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: super-linter-log
-          path: super-linter.log
+          name: super-linter-output
+          path: super-linter-output/
